-- The statuses a workspace's issues move through, decided by the workspace.
--
-- Until now the four of them were an enum in code, and a workspace that wanted
-- "won't fix" or "needs information" said it in a label - which is a set, and a
-- set cannot be the answer to "where is this". So the list is a table, one row
-- per status per workspace, in the shape the issue types took in V197 and for
-- the same reasons: it exists while nothing holds it, it can be renamed in one
-- place, and it is the workspace's own. Issue #428.
--
-- The issue keeps holding a key rather than pointing at a row, so the column is
-- exactly what it was with the enum's four names still in it - widened, because
-- a key a workspace types is longer than the sixteen characters the enum needed.
-- Every write checks the key against this table in code; the history and the
-- news keep the key too, because a key never changes and a label does.
CREATE TABLE workspace_issue_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    -- Upper snake case: REVIEW, WONTFIX, NEEDS_INFO. What an issue stores and a
    -- tool call names, so it is never changed once it exists.
    key VARCHAR(32) NOT NULL,

    -- What people read. As long as a type's name, since the two sit side by side.
    label VARCHAR(60) NOT NULL,

    -- A CSS colour for the dot and the badge, or null for the interface's own.
    color VARCHAR(32),

    -- Display order: the list, the filter bar, and the cycle the status button walks.
    position INT NOT NULL DEFAULT 0,

    -- Where a new issue lands. Exactly one per workspace; the index below says so.
    initial BOOLEAN NOT NULL DEFAULT FALSE,

    -- Counts as done. Any number of them: fixed and won't-fix are both finished.
    closed BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One REVIEW per workspace however it is capitalised, for the reason a type's
-- name is unique that way: two rows a reader cannot tell apart collect issues
-- between them by accident.
CREATE UNIQUE INDEX workspace_issue_status_key_key ON workspace_issue_status (workspace_id, upper(key));

-- Exactly one place a new issue can land.
CREATE UNIQUE INDEX workspace_issue_status_initial_key ON workspace_issue_status (workspace_id) WHERE initial;

CREATE INDEX workspace_issue_status_workspace_idx ON workspace_issue_status (workspace_id, position);

-- Room for a key somebody types. The four the enum had all fit in sixteen; a
-- workspace's own do not have to.
ALTER TABLE workspace_issue ALTER COLUMN status TYPE VARCHAR(32);

-- The four every workspace already has, written down for every workspace that
-- already exists - so not one issue changes and not one filter reads
-- differently tomorrow. New workspaces are given the same four in code when
-- they are made, so both engines say the same thing. No colours: the interface
-- knows these keys and draws them as it always did.
INSERT INTO workspace_issue_status (workspace_id, key, label, position, initial, closed)
    SELECT id, 'OPEN', 'Open', 0, TRUE, FALSE FROM workspace;
INSERT INTO workspace_issue_status (workspace_id, key, label, position, initial, closed)
    SELECT id, 'IN_PROGRESS', 'In progress', 1, FALSE, FALSE FROM workspace;
INSERT INTO workspace_issue_status (workspace_id, key, label, position, initial, closed)
    SELECT id, 'REVIEW', 'Review', 2, FALSE, FALSE FROM workspace;
INSERT INTO workspace_issue_status (workspace_id, key, label, position, initial, closed)
    SELECT id, 'CLOSED', 'Closed', 3, FALSE, TRUE FROM workspace;
