-- The size presets a workspace's image nodes pick from, decided by the workspace.
--
-- An image node whose model takes free dimensions - anything self-hosted behind
-- an OpenAI-shaped endpoint - asks for a width and a height, and typing 1024
-- twice into every node is what a menu is for. The menu is the workspace's: the
-- team drawing catalogue thumbnails puts its 600x400 first, the one drawing
-- posters wants nothing under 2048. So it is a table, one row per preset per
-- workspace, in the shape the issue statuses took in V296 and for the same
-- reasons: it can be renamed in one place, reordered, and it is the workspace's
-- own. Issue #431.
--
-- A node stores the numbers a preset filled in, never the preset, so a preset
-- renamed or removed changes no saved node and nothing here is referenced.
CREATE TABLE workspace_image_size_preset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    -- What the menu says: "Landscape 1536". As long as a status label is.
    name VARCHAR(60) NOT NULL,

    -- Pixels. Held in code to 1..8192 each.
    width INT NOT NULL,
    height INT NOT NULL,

    -- Menu order.
    position INT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX workspace_image_size_preset_workspace_idx ON workspace_image_size_preset (workspace_id, position);

-- The seven sizes the two OpenAI image families draw between them, written down
-- for every workspace that already exists, so the menu is full tomorrow. New
-- workspaces are given the same seven in code when they are made, so both
-- engines say the same thing.
INSERT INTO workspace_image_size_preset (workspace_id, name, width, height, position)
    SELECT id, 'Square 1024', 1024, 1024, 0 FROM workspace;
INSERT INTO workspace_image_size_preset (workspace_id, name, width, height, position)
    SELECT id, 'Landscape 1536', 1536, 1024, 1 FROM workspace;
INSERT INTO workspace_image_size_preset (workspace_id, name, width, height, position)
    SELECT id, 'Portrait 1536', 1024, 1536, 2 FROM workspace;
INSERT INTO workspace_image_size_preset (workspace_id, name, width, height, position)
    SELECT id, 'Wide 1792', 1792, 1024, 3 FROM workspace;
INSERT INTO workspace_image_size_preset (workspace_id, name, width, height, position)
    SELECT id, 'Tall 1792', 1024, 1792, 4 FROM workspace;
INSERT INTO workspace_image_size_preset (workspace_id, name, width, height, position)
    SELECT id, 'Square 512', 512, 512, 5 FROM workspace;
INSERT INTO workspace_image_size_preset (workspace_id, name, width, height, position)
    SELECT id, 'Square 256', 256, 256, 6 FROM workspace;
