-- What arrives at a session while nobody is looking: an agent it asked
-- answering, a timer it set coming due. Issue: an agent delegated, said it
-- would check back later, and finished - and nothing ever brought it back.
--
-- One row per event. The session reads what is due between rounds of a turn
-- that is running; one that is not running is woken by it. `due_at` is when it
-- may be delivered - now for an answer, later for a timer - and `delivered_at`
-- stays null until the agent has been shown it, so an event is read once.

CREATE TABLE session_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id BIGINT NOT NULL REFERENCES llm_session (id) ON DELETE CASCADE,

    kind VARCHAR(16) NOT NULL,

    /* What the agent is told, in full. */
    body TEXT NOT NULL,

    due_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_session_event_kind CHECK (kind IN ('ANSWER', 'TIMER'))
);

CREATE INDEX ix_session_event_waiting ON session_event (session_id, due_at) WHERE delivered_at IS NULL;
CREATE INDEX ix_session_event_due ON session_event (due_at) WHERE delivered_at IS NULL;
