package io.mszymanski.orknux.server.plugin

import io.mszymanski.orknux.server.action.WorkflowFunction
import io.mszymanski.orknux.server.action.WorkflowFunctionRepository
import io.mszymanski.orknux.server.graphql.Refusal
import org.springframework.stereotype.Service

/**
 * Folds a plugin's edited functions back over its bundle, for the export.
 *
 * A bundle is what its author uploaded; an edit lives on the function row and
 * never rewrites the artifact. But "export the plugin" means the plugin as this
 * installation runs it, edits and all, so the download builds a bundle that
 * says so: the original class, subclassed, with each edited declaration's
 * `run` replaced by the edited code.
 *
 * The edited code is a module - `export default function …` with whatever
 * helpers around it - and it is folded in as an IIFE with that export turned
 * into an assignment, so helpers before and after the export both survive.
 * The one thing that cannot be folded is a bundle whose `export default`
 * cannot be found, and that is refused in words rather than exported broken.
 */
@Service
class PluginOverrides(
    private val functions: WorkflowFunctionRepository,
    private val sources: PluginSources,
) {

    /** The plugin's functions somebody edited; empty for a plugin nobody touched. */
    fun editedOf(plugin: Plugin): List<WorkflowFunction> =
        functions.findByPluginId(requireNotNull(plugin.id)).filter { it.editedAt != null }

    /** The bundle with [edited] folded over it, or null where it cannot be. */
    fun folded(plugin: Plugin, edited: List<WorkflowFunction>): String? {
        val source = sources.sourceOf(plugin)
        val at = source.indexOf(EXPORTED)
        if (at < 0) return null

        val declared = source.replaceRange(at, at + EXPORTED.length, "const $ORIGINAL =")

        val entries = edited.joinToString(",\n") { function ->
            // teammates_isTeammate -> isTeammate: the name the declaration
            // carries, which is what functions() answers with.
            val name = function.name.removePrefix("${plugin.key}_")
            val body = function.source.replaceFirst(EXPORTED, "const $EDIT =")
            "  \"$name\": (function () {\n$body\nreturn $EDIT;\n  })()"
        }

        return buildString {
            append(declared)
            append("\n\n")
            append("// --- Edits made on this installation, folded over the declarations above.\n")
            append("// Each replaces the run of the function it names; everything else is the\n")
            append("// author's bundle as uploaded. Generated by the export - edit the function,\n")
            append("// not this block.\n")
            append("const $EDITS = {\n")
            append(entries)
            append("\n};\n\n")
            append("export default class extends $ORIGINAL {\n")
            append("  functions() {\n")
            append("    return super.functions().map((declared) => {\n")
            append("      const edit = $EDITS[declared.name];\n")
            append("      if (edit) declared.run = edit;\n")
            append("      return declared;\n")
            append("    });\n")
            append("  }\n")
            append("}\n")
        }
    }

    private companion object {
        const val EXPORTED = "export default"
        const val ORIGINAL = "__orknuxDeclared"
        const val EDIT = "__orknuxEdit"
        const val EDITS = "__orknuxEdits"
    }
}

/** The bundle's own export could not be found, so nothing could be folded over it. */
class PluginExportUnfoldableException(val name: String) : RuntimeException(
    "$name has edited functions, but its bundle's `export default` could not be found to fold them over - " +
        "download the original and carry the edits by hand",
), Refusal {

    override val arguments get() = mapOf("name" to name)
}
