package io.mszymanski.orknux.connector.model

import io.mszymanski.orknux.connector.Unreachable
import io.mszymanski.orknux.connector.connection.ConnectionProbe
import io.mszymanski.orknux.connector.proxy.ProxyRouter
import com.openai.errors.OpenAIServiceException
import org.slf4j.LoggerFactory
import org.springframework.data.repository.findByIdOrNull
import org.springframework.stereotype.Service
import java.net.URI
import java.net.http.HttpClient
import java.time.Duration

/** What came back from a reading, or why nothing did. */
sealed interface Speech {

    /**
     * The audio itself, and what it is.
     *
     * The bytes are handed straight to whoever asked rather than stored: an
     * answer read aloud is listened to once, and keeping it would mean a second
     * copy of the conversation in a different medium.
     */
    data class Spoke(val audio: ByteArray, val contentType: String, val millis: Long) : Speech {

        /*
         * Generated by hand because the array makes the compiler's version wrong:
         * two readings of the same sentence are not the same object, and
         * `equals` comparing references would say they were different anyway.
         * Identity is what this has, so identity is what it declares.
         */
        override fun equals(other: Any?): Boolean = this === other

        override fun hashCode(): Int = System.identityHashCode(this)
    }

    data class Failed(val reason: String) : Speech
}

/**
 * Reads text aloud, using one of the workspace's models.
 *
 * The mirror of [ModelTranscriptionClient], and deliberately its twin: the same
 * providers, the same credential, the same failure vocabulary. OpenAI's
 * `/audio/speech` is the shape spoken by OpenAI itself, by Azure's OpenAI
 * deployments, and by the local servers that imitate them — a JSON body naming
 * the model, the text and a voice, answering with the audio as bytes.
 *
 * Unlike transcription this sends JSON rather than multipart, because what goes
 * up is a sentence; it is the answer that is binary.
 */
@Service
class ModelSpeechClient(
    private val providers: ModelProviderRepository,
    private val models: LlmModelRepository,
    private val media: OpenAiMedia,
    private val connections: ConnectionProbe,
    private val proxies: ProxyRouter,
) {

    private val http: HttpClient = proxies.builder()
        .version(HttpClient.Version.HTTP_1_1)
        .connectTimeout(Duration.ofSeconds(CONNECT_SECONDS))
        // Said out loud rather than left to the default, because it is the same
        // rule the chat client and the probe state: a redirect can leave the
        // host somebody configured and take the key with it.
        .followRedirects(HttpClient.Redirect.NEVER)
        .build()

    /**
     * @param modelId one of the workspace's models, which has to be a speech
     *   one: a chat model handed this would answer *about* the text instead of
     *   reading it.
     * @param voice which voice to use, or null for the model's own default —
     *   the providers disagree about what voices exist, so an installation that
     *   has not chosen one should not have a name invented for it.
     */
    fun speak(modelId: Long, text: String, voice: String?): Speech {
        val model = models.findByIdOrNull(modelId)
            ?: return Speech.Failed("That model no longer exists")
        if (model.kind != ModelKind.SPEECH) {
            return Speech.Failed("${model.name} is not a speech model")
        }
        if (!model.enabled) return Speech.Failed("${model.name} is turned off")

        val said = text.trim()
        if (said.isEmpty()) return Speech.Failed("There is nothing to read")

        val provider = providers.findByIdOrNull(model.providerId)
            ?: return Speech.Failed("The provider ${model.name} belongs to has been removed")

        // Off the OpenAI surface rather than off the endpoint, for the reason
        // [ModelProvider.openAiBase] gives: on some types they are not the same place.
        val endpoint = "${provider.openAiBase()}/audio/speech"
        val uri = try {
            URI(endpoint)
        } catch (_: Exception) {
            return Speech.Failed("The provider endpoint is not a usable URL")
        }

        /*
         * Where this is going is asked about here rather than only behind the
         * "Test provider" button, because the credential goes with it and a
         * check nobody has to press is not a check. [ConnectionProbe] decides,
         * the same rule the connection probe applies, and the refusal comes
         * back as the failure the reading button reports - which is where the
         * person who set the endpoint is looking. Asked before the credential
         * is resolved, so a call that will not be made fetches nothing.
         */
        connections.vet(endpoint)?.let { return Speech.Failed("${provider.name} cannot be called: $it") }

        val started = System.currentTimeMillis()
        return try {
            when (val spoken = media.speak(provider, model, said, voice)) {
                is OpenAiMedia.Spoken.Failed -> Speech.Failed(spoken.reason)
                is OpenAiMedia.Spoken.Audio -> {
                    val millis = System.currentTimeMillis() - started
                    if (spoken.bytes.isEmpty()) {
                        Speech.Failed("${model.name} answered nothing")
                    } else {
                        // The SDK decodes the refusal shapes; what reaches here
                        // is audio or an exception, so the content type is the
                        // one that was asked for.
                        Speech.Spoke(audio = spoken.bytes, contentType = "audio/$FORMAT", millis = millis)
                    }
                }
            }
        } catch (refused: OpenAIServiceException) {
            log.warn("Speech by {} at {} answered {}", model.name, endpoint, refused.statusCode())
            Speech.Failed(refused.message ?: "${model.name} answered ${refused.statusCode()}")
        } catch (failure: Exception) {
            log.warn("Speech by {} at {} could not be done", model.name, endpoint, failure)
            Speech.Failed(Unreachable.describe(endpoint, failure))
        }
    }

    private companion object {
        val log = LoggerFactory.getLogger(ModelSpeechClient::class.java)

        /**
         * What to ask for.
         *
         * MP3 because every browser plays it, and because it is the one format
         * all of these providers offer — wav is smaller to decode but several
         * times the bytes over the wire for something that is only listened to.
         */
        const val FORMAT = "mp3"

        const val CONNECT_SECONDS = 10L
        const val REQUEST_SECONDS = 120L
    }
}
